Import-Module $PSScriptRoot\CtDeviceAppManagement.psm1 -Force
Connect-CtDeviceAppManagement

Remove-CtMgDeviceAppManagementMobileApp "iOS" "Adobe Acrobat Reader"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Authenticator"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Bookings"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Edge"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Excel"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Office"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft OneDrive"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft OneNote"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Outlook"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft PowerPoint"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft SharePoint"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Teams"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft To Do"
Remove-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Word"
Remove-CtDeviceAppManagementiOSManagedAppProtection "Default Mobile App Policy for iOS devices"

Remove-CtMgDeviceAppManagementMobileApp "Android" "Adobe Acrobat Reader"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Authenticator"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Bookings"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Edge"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Excel"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Office"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft OneDrive"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft OneNote"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Outlook"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft PowerPoint"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft SharePoint"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Teams"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft To Do"
Remove-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Word"
Remove-CtDeviceAppManagementAndroidManagedAppProtection "Default Mobile App Policy for Android devices"