Import-Module $PSScriptRoot\CtDeviceAppManagement.psm1 -Force
Connect-CtDeviceAppManagement

Test-CtMgDeviceAppManagementMobileApp "iOS" "Adobe Acrobat Reader"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Authenticator"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Bookings"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Edge"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Excel"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Office"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft OneDrive"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft OneNote"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Outlook"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft PowerPoint"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft SharePoint"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Teams"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft To Do"
Test-CtMgDeviceAppManagementMobileApp "iOS" "Microsoft Word"
Test-CtDeviceAppManagementiOSManagedAppProtection "Default Mobile App Policy for iOS devices"

Test-CtMgDeviceAppManagementMobileApp "Android" "Adobe Acrobat Reader"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Authenticator"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Bookings"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Edge"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Excel"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Office"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft OneDrive"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft OneNote"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Outlook"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft PowerPoint"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft SharePoint"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Teams"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft To Do"
Test-CtMgDeviceAppManagementMobileApp "Android" "Microsoft Word"
Test-CtDeviceAppManagementAndroidManagedAppProtection "Default Mobile App Policy for Android devices"